services:
  torrentarr:
    build: .
    container_name: torrentarr
    labels:
    - "net.unraid.docker.icon=/mnt/user/appdata/torrentarr/icon.png"
    stdin_open: true
    tty: true
    working_dir: /config
    env_file:
      - ./config.env
    volumes:
      - /path/to/your/media:/MEDIA:rw
      - /output/for/your/torrents:/TORRENTS:rw
      - /mnt/user/appdata/torrent-creator:/config:rw
      - /tmp:/tmp
    restart: "no"
